### ISSUE TITLE
Class 'CK\MARCspec' not found

### ISSUE THREAD

**Issue by yfhui** [MARCspec/php-marc-spec#11]
I used composer to install the package and when I run the demo, it told me that "Class 'CK\MARCspec' not found", any hint to solve this problem? Or is package having some compatibility issue?

**Comment by cKlee** [comment]
I'm so sorry for the faulty example. I've updated the README. In your demo file use classes like:

```php
<?php
require("vendor/autoload.php");

use CK\MARCspec\MARCspec;
use CK\MARCspec\Field;
use CK\MARCspec\Subfield;
use CK\MARCspec\ComparisonString;
use CK\MARCspec\SubSpec;
```

**Comment by yfhui** [comment]
I can use the package now, thanks
but one more extra question, I am testing with the following codes but I was returned that setTag function is not found, and I checked the source code indeed you write to call a setTag function, but the function is missing
My testing code:
```php
require "vendor/autoload.php";
use CK\MARCspec\MARCspec;
use CK\MARCspec\Field;
use CK\MARCspec\Subfield;
use CK\MARCspec\ComparisonString;
use CK\MARCspec\SubSpec;
$fixed = new MARCspec('007[0]/1-8{/0=\a}');
echo $fixed['field'];
$fixed['field']['tag'] = "003";
echo $fixed['field'];  
```
The error I got:
`Uncaught Error: Call to undefined method CK\MARCspec\Field::setTag()`

**Comment by cKlee** [comment]
Thanks for reporting! `setTag` was a legacy method call. I will erase it.

The idea behind it is, that you cannot change the tag of a field. This is because other definition might depend on the field tag. And if the field tag changes, all depndents have to be changed.

Is this problematic for your task. Or are you just testing?

**Comment by yfhui** [comment]
yes I am just testing, because I am looking for a package that can alter the subfields easily, other than using the FILE_MARC pear package. Thanks for your help anyway!
